Repository TomMonty/minday, pull requests merged in 2025-05, with the labels that each got.

#10 New feature Bottom Nav
  src/components/BottomNav/BottomNav.jsx
  src/components/BottomNav/BottomNav.module.css
Labels: enhancement

#12 New Feature Category Grid
  src/App.css
  src/components/Card.js
  src/components/CategoryGrid/CategoryGrid.jsx
  src/components/CategoryGrid/CategoryGrid.module.css
  src/data/cards.js
  src/pages/Minday.js
Labels: enhancement

#13 New feature deck component
  src/components/Deck/Deck.jsx
  src/components/Deck/Deck.module.css
Labels: enhancement

#16 New feature quizz logic
  src/components/QuizQuestion/QuizQuestion.jsx
  src/components/QuizQuestion/QuizQuestion.module.css
  src/components/Results/Results.jsx
  src/components/Results/Results.module.css
  src/components/VersusHeader/VersusHeader.jsx
  src/components/VersusHeader/VersusHeader.module.css
Labels: enhancement

#17 New feature ui components
  src/components/ui/accordion.jsx
  src/components/ui/alert-dialog.jsx
  src/components/ui/alert.jsx
  src/components/ui/aspect-ratio.jsx
  src/components/ui/avatar.jsx
  src/components/ui/badge.jsx
  src/components/ui/breadcrumb.jsx
  src/components/ui/button.jsx
  src/components/ui/calendar.jsx
  src/components/ui/card.jsx
  src/components/ui/carousel.jsx
  src/components/ui/chart.jsx
Labels: enhancement

#18 New ui components
  src/components/ui/checkbox.jsx
  src/components/ui/collapsible.jsx
  src/components/ui/command.jsx
  src/components/ui/context-menu.jsx
  src/components/ui/dialog.jsx
  src/components/ui/drawer.jsx
  src/components/ui/dropdown-menu.jsx
  src/components/ui/form.jsx
  src/components/ui/hover-card.jsx
  src/components/ui/input-otp.jsx
  src/components/ui/input.jsx
  src/components/ui/label.jsx
  src/components/ui/menubar.jsx
  src/components/ui/navigation-menu.jsx
  src/components/ui/pagination.jsx
  src/components/ui/popover.jsx
  src/components/ui/progress.jsx
Labels: enhancement

#19 Added even more ui components
  src/components/ui/radio-group.jsx
  src/components/ui/resizable.jsx
  src/components/ui/scroll-area.jsx
  src/components/ui/select.jsx
  src/components/ui/separator.jsx
  src/components/ui/sheet.jsx
  src/components/ui/sidebar.jsx
  src/components/ui/skeleton.jsx
  src/components/ui/slider.jsx
  src/components/ui/sonner.jsx
  src/components/ui/switch.jsx
  src/components/ui/table.jsx
  src/components/ui/tabs.jsx
  src/components/ui/textarea.jsx
  src/components/ui/toast.jsx
  src/components/ui/toaster.jsx
  src/components/ui/toggle-group.jsx
  src/components/ui/toggle.jsx
  src/components/ui/tooltip.jsx
  src/components/ui/use-toast.ts.jsx
Labels: enhancement

#20 New feature profile component
  src/components/Profile/AvatarUploader.jsx
  src/components/Profile/AvatarUploader.module.css
Labels: enhancement

#21 Modified data to app context and added more mock data
  src/context/AppContext.jsx
  src/data/cards.js
Labels: enhancement

#22 Hooks directory
  src/hooks/use-mobile.jsx
  src/hooks/use-toast.jsx
  src/hooks/useStreak.jsx
Labels: enhancement

#24 Fix Pages Directory
  src/pages/Challenges.js
  src/pages/Challenges/ChallengeGame.jsx
  src/pages/Challenges/ChallengeGame.module.css
  src/pages/Challenges/ChallengeLobby.jsx
  src/pages/Challenges/ChallengeLobby.module.css
  src/pages/Challenges/Challenges.jsx
  src/pages/Home/Home.jsx
  src/pages/Index.jsx
  src/pages/Librairie.js
  src/pages/Library/DetailPage.jsx
  src/pages/Library/DetailPage.module.css
  src/pages/Library/Library.jsx
  src/pages/Library/ListPage.jsx
  src/pages/Library/ListPage.module.css
  src/pages/Minday.js
  src/pages/NotFound.jsx
  src/pages/Profil.js
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Profile.module.css
  src/pages/SplashScreen/SplashScreen.jsx
  src/pages/SplashScreen/SplashScreen.module.css
Labels: bug, documentation, enhancement, question

#25 Before Service Mock Data Test
  src/services/serviceCards.jsx
  src/services/serviceLibrary.jsx
  src/services/serviceQuiz.jsx
  src/services/serviceUser.jsx
Labels: bug, enhancement

#26 File's fix on the src
  src/App.css
  src/App.js
  src/App.jsx
  src/App.test.js
  src/components/BottomNav/BottomNav.module.css
  src/components/Card.js
  src/components/Card/Card.module.css
  src/components/Deck/Deck.module.css
  src/components/LoadingScreen.js
  src/components/Navbar.js
  src/index.css
  src/index.js
  src/lib/utils.jsx
  src/logo.svg
  src/main.jsx
  src/pages/Index.jsx
  src/reportWebVitals.js
  src/setupTests.js
Labels: bug

#28 Final-Touches-Before-Main
  README.md
  backend/deleteAllSavedCards.js
  backend/resetSavedCards.js
  backend/routes/savedCardRoutes.js
  backend/testDeleteCard.js
  src/components/Card/Card.module.css
  src/components/CardDetail/CardDetail.jsx
  src/components/CardDetail/CardDetail.module.css
  src/pages/Challenges/ChallengeLobby.jsx
  src/pages/Home/Home.jsx
  src/pages/Library/DetailPage.jsx
Labels: bug, enhancement, help wanted

#32 Detail-miniCards-Challenge
  frontend/.gitignore
  src/App.jsx
  src/components/MiniCard/MiniCard.jsx
  src/pages/Challenges/ChallengeGame.module.css
  src/pages/Challenges/ChallengeLobby.jsx
  src/pages/Challenges/ChallengeLobby.module.css
  src/pages/Challenges/Challenges.jsx
  src/pages/Challenges/Challenges.module.css
  src/pages/Library/DetailPage.jsx
Labels: enhancement
